# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - DPhelpdesk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://aiacr2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca656c1314f74cbab5463f8c831c574f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2d3e98b468d845b782cf00b6b2528105 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: aiacr2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca656c1314f74cbab5463f8c831c574f }}/sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'DPhelpdesk'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_102d3b58b1f64b548b80a8be00224b69 }}
        images: 'aiacr2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca656c1314f74cbab5463f8c831c574f }}/sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:${{ github.sha }}'